---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "cicd-deployment"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "integration"
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
    type: "RollingUpdate"
  template:
    metadata:
      labels:
        app: "integration"
    spec:
      containers:
      - name: "micro-integrator"
        image: "kngone/dashjen:${project.version}"
        imagePullPolicy: "Always"
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "cicd-service"
spec:
  type: "ClusterIP"
  selector:
    app: "integration"
  ports:
  - name: "cicd-management-http-port"
    port: 9201
    targetPort: 9201
  - name: "cicd-pt-httpsport"
    port: 8253
    targetPort: 8253
  - name: "cicd-pt-httpport"
    port: 8290
    targetPort: 8290
  - name: "cicd-management-https-port"
    port: 9164
    targetPort: 9164
